### ISSUE TITLE
Hard Deletions Tracking Issue

### ISSUE THREAD

**Issue by mdibaiee** [estuary/connectors#1620]
Captures
- [ ] source-airtable
- [ ] source-alpaca
- [ ] source-asana
- [ ] source-azure-blob-storage
- [ ] source-bigquery-batch
- [ ] source-criteo
- [ ] source-dynamodb
- [ ] source-facebook-marketing
- [ ] source-firestore
- [ ] source-gcs
- [ ] source-gladly
- [ ] source-google-ads
- [ ] source-google-drive
- [ ] source-google-sheets-native
- [ ] source-hello-world
- [ ] source-http-file
- [ ] source-http-ingest
- [ ] source-hubspot
- [ ] source-hubspot-native
- [ ] source-kafka
- [ ] source-kinesis
- [ ] source-linkedin-pages
- [ ] source-mongodb
- [ ] source-mysql
- [ ] source-mysql-batch
- [ ] source-notion
- [ ] source-oracle
- [ ] source-pokemon
- [ ] source-postgres
- [ ] source-postgres-batch
- [ ] source-redshift-batch
- [ ] source-s3
- [ ] source-sftp
- [ ] source-shopify
- [ ] source-snowflake
- [ ] source-sqlserver
- [ ] source-yahoo-finance

Materializations:
- [ ] materialize-bigquery
- [ ] materialize-databricks
- [ ] materialize-dynamodb
- [ ] materialize-elasticsearch
- [ ] materialize-firebolt
- [ ] materialize-google-pubsub
- [ ] materialize-google-sheets
- [ ] materialize-mongodb
- [ ] materialize-motherduck
- [ ] materialize-mysql
- [ ] materialize-pinecone
- [ ] materialize-postgres
- [ ] materialize-redshift
- [ ] materialize-rockset
- [ ] materialize-s3-parquet
- [ ] materialize-snowflake
- [ ] materialize-sqlite
- [ ] materialize-sqlserver
- [ ] materialize-starburst
- [ ] materialize-webhook

**Comment by williamhbaker** [comment]
I checked off some of the source systems that do not have a concept of deletions (ex: `filesource` captures) and also some materializations that are delta updates only.

**Comment by williamhbaker** [comment]
On the capture side, `source-mongodb` and `source-dynamodb` seem like they'd be worth doing sooner or later, especially since `source-mongodb` is quite widely used.
